#!/usr/bin/env bash

set -e

9 9p read plumb/edit |while true; do
  read -r src
  read -r dst
  read -r wdir
  read -r type
  read -r attrs
  read -r ndata
  read -N $ndata data

  client='%opt{jumpclient}'
  evaluate=""
  session=""
  eval set -- "$attrs"
  while [[ $# -ne 0 ]]; do
    case "$1" in
      client=*)   client="''${1#client=}";;
      evaluate=*) evaluate="''${1#evaluate=}";;
      session=*)  session="''${1#session=}";;
    esac
    shift
  done

  printf '
    evaluate-commands -try-client %s %%{
      try %%{
        %s
        try focus
      } catch %%{
        echo -markup "{Error}%val{error}"
        echo -debug "%val{error}"
      }
    }
  ' "$client" "$evaluate" |kak -p "$session"
done
